version: '3.4'
services:
  linuxgsm:
    image: "ghcr.io/gameservermanagers/linuxgsm-docker:latest"
    container_name: sdtdserver
    environment:
      - GAMESERVER=sdtdserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - /opt/sdtdserver/serverfiles:/home/linuxgsm/serverfiles
      - /opt/sdtdserver/log:/home/linuxgsm/log
      - /opt/sdtdserver/config-lgsm:/home/linuxgsm/lgsm/config-lgsm
    ports:
      - "26900:26900/tcp"
      - "26900:26903/udp"
    restart: unless-stopped
